# Generated by Django 3.1.5 on 2021-01-12 13:07

from django.db import migrations, models
import recognization.models
import recognization.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OCR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=recognization.utils.random_image_name)),
                ('result', models.JSONField()),
            ],
        ),
    ]
